# Generated by Django 4.1.13 on 2024-02-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default quiz', max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
